config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers

  get '/products/search', to: 'products#search'
  get '/products/buy/:variant_id', to: 'products#buy'
  get '/orders/current', to: 'orders#current'
  post '/orders/current', to: 'orders#pay'
  get '/orders', to: 'orders#index'

  resources :products do
    resources :comments
  end

  root 'products#index'

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :variants, :through => :orders
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :products
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orders_has_variants
  has_many :variants, :through => :orders_has_variants
  belongs_to :buyer
end

app/models/orders_has_variant.rb
class OrdersHasVariant < ActiveRecord::Base
  belongs_to :order
  belongs_to :variant
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :channel
  has_many :variants
  has_many :comments
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :product
  has_many :orders_has_variants
  has_many :variants, :through => :orders_has_variants
  has_many :buyers, :through => :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.create(comment_params)
		redirect_to product_path(@product)
	end

	private
	def comment_params
	  params.require(:comment).permit(:user_name, :text)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = current_buyer.orders
  end

  def current
    @totalPrice = 0
    @hasToPay = true
    ids = session[:variant_ids]
    @variantsToBuy = Array.new

    if !ids.nil?
      ids.each do |id|
        @variantsToBuy << Variant.find(id.to_i)
      end
    else
      @hasToPay = false
    end

  end

  def pay
    total = 0
    newOrder = Order.new(buyer_id: current_buyer.id)

    if !session[:variant_ids].nil?
      session[:variant_ids].each do |id|
        variant = Variant.find(id)
        newOrder.variants << variant
        total += variant.price
        variant.quantity -= 1
        variant.save
      end

      newOrder.save
      current_buyer.credits -= total
      current_buyer.save
      session[:variant_ids] = nil
    end


    redirect_to "/orders"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @channels = Channel.all
    if(params[:channel].blank?)
      @products = Channel.find(1).products.all
    else
      @products = Channel.find(params[:channel]).products.all
    end
  end

  def search
    if(params[:q].blank?)
			@products = Product.all
		else
			@products = Product.where("name like '%" + params[:q] + "%'")
		end
  end

  def show
    @product = Product.find(params[:id])
    @variants = @product.variants.all
    @comments = @product.comments.all
  end

  def buy
    s = Set.new


    if !session[:variant_ids].nil?
      session[:variant_ids].each do |id|
        s << id
      end
    end

    s << params[:variant_id]
    session[:variant_ids] = s

    redirect_to "/orders/current"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/current.html.erb
<h3> Current Order </h3>


<ul>
  <% @variantsToBuy.each do |variant| %>
  <li>
    Product: <%= Product.find(variant.product_id).name %>
  </li>
  <li>
    Price: <%= variant.price %>
    <% @totalPrice += variant.price %>
  </li>
  <% end %>
  <br>
  <li>
    Total: <%= @totalPrice %>
  </li>
</ul>

<%= button_to "Pay", action: "pay" %>

<%= link_to "Back", products_path %>

app/views/orders/index.html.erb
<h3> Orders </h3>

<ul>
  <% @orders.each do |order| %>
    <h4> Order ID: <%= order.id %> </h4>
      <% order.variants.each do |variant| %>
        <li> Product: <%= Product.find(variant.product_id).name %> </li>
        <li> Price: <%= variant.price %> </li>
      <% end %>
  <% end %>
  <br>
</ul>

<%= link_to "Index", products_path %>

app/views/products/_form.html.erb
<%= form_for([@product, @product.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %> <br>
    <%= f.text_field :user_name %>
  </p>
  <p>
    <%= f.label :text %> <br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/index.html.erb
<h1> Index </h1>

<%= form_tag("/products/search", method: "get", class: "search") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<span>
  <% @channels.each do |channel| %>
      <%= link_to channel.name, controller: "products", channel: channel.id %>
  <% end %>
  <%= link_to "Pay", "/orders/current" %>
</span>

<ul>
	<% @products.each do |product| %>
      <strong> <%= link_to product.name, product_path(product.id) %> </strong>
      <li>
    		Price: <%= product.variants.order(price: :desc).last.price %>
      </li>
      <li>
        Quantity: <%= product.variants.order(price: :desc).last.quantity %>
    	</li>
      <% if buyer_signed_in? %>
        <%= link_to 'Buy', action: "buy", variant_id: product.variants.order(price: :desc).last.id %>
      <% end %>
      <br>
  <% end %>
</ul>

<% if buyer_signed_in? %>
  <%= link_to('Sign out!', destroy_buyer_session_path, :method => :delete) %>
<% else %>
  <%= link_to('Sign in!', new_buyer_session_path) %>
<% end %>

app/views/products/search.html.erb
<h2> Query result: </h2>

<ul>
  <% @products.each do |product| %>
    <h4> <%= product.name %> </h4>
    <li>
      Price: <%= product.variants.order(price: :asc).first.price %>
    </li>
    <li>
      Quantity: <%= product.variants.order(price: :asc).first.quantity %>
    </li>
    <% if buyer_signed_in? %>
      <%= link_to 'Buy', action: "buy", variant_id: product.variants.order(price: :desc).last.id %>
    <% end %>
    <br>
  <% end %>
</ul>

<%= link_to('Index', products_path) %>

app/views/products/show.html.erb
<h2> <%= @product.name %> </h2>

<h4> Description: </h4>
<p> <%= @product.description %> </p>

<h4> Variants: </h4>

<ul>
  <% @variants.each do |variant| %>
    <li>
      Price: <%= variant.price %>
    </li>
    <li>
      Quantity: <%= variant.quantity %>
    </li>
    <% if buyer_signed_in? %>
      <%= link_to 'Buy', action: "buy", variant_id: variant.id %>
    <% end %>
  <% end %>
</ul>

<h3> Comments: </h3>

<ul>
  <% @comments.each do |comment| %>
    <h4> <%= comment.user_name %> said: </h4>
    <p>
      <%= comment.text %>
    </p>
  <% end %>
</ul>

<%= render "form" %>